"""empty message

Revision ID: 1f3e55a73eba
Revises: 6fbdc606465c
Create Date: 2017-05-06 20:47:40.689434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3e55a73eba'
down_revision = '6fbdc606465c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('hashtag_filter', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('owner_username', sa.String(), nullable=True))
    op.add_column('disabled_channels', sa.Column('last_vk_post_id', sa.Integer(), nullable=True))
    op.add_column('disabled_channels', sa.Column('owner_id', sa.String(), nullable=True))
    op.add_column('disabled_channels', sa.Column('owner_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disabled_channels', 'owner_username')
    op.drop_column('disabled_channels', 'owner_id')
    op.drop_column('disabled_channels', 'last_vk_post_id')
    op.drop_column('channels', 'owner_username')
    op.drop_column('channels', 'hashtag_filter')
    # ### end Alembic commands ###
