"""empty message

Revision ID: 215a632cdf23
Revises: f5f69376d382
Create Date: 2017-07-09 17:04:22.228617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215a632cdf23'
down_revision = 'f5f69376d382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disabled_channels', sa.Column('channel_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disabled_channels', 'channel_id')
    # ### end Alembic commands ###
