"""empty message

Revision ID: 2e8d45ad3ac3
Revises: 97bba2b7506c
Create Date: 2017-07-10 01:04:39.286233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8d45ad3ac3'
down_revision = '97bba2b7506c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
