"""empty message

Revision ID: 5cc020d19560
Revises: c350a71fcf2b
Create Date: 2017-05-01 13:05:26.215677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc020d19560'
down_revision = 'c350a71fcf2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('last_vk_post_id', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'last_vk_post_id')
    # ### end Alembic commands ###
