"""empty message

Revision ID: 6fbdc606465c
Revises: c2939c48f11f
Create Date: 2017-05-01 14:44:26.707567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fbdc606465c'
down_revision = 'c2939c48f11f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('owner_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'owner_id')
    # ### end Alembic commands ###
