"""empty message

Revision ID: 97bba2b7506c
Revises: 215a632cdf23
Create Date: 2017-07-09 17:05:36.617297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97bba2b7506c'
down_revision = '215a632cdf23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('disabled_channels', 'channel_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('disabled_channels', 'last_vk_post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('disabled_channels', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('disabled_channels', 'vk_group_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disabled_channels', 'vk_group_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('disabled_channels', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('disabled_channels', 'last_vk_post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('disabled_channels', 'channel_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('channels', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
