"""empty message

Revision ID: c2939c48f11f
Revises: 5cc020d19560
Create Date: 2017-05-01 13:24:16.253686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2939c48f11f'
down_revision = '5cc020d19560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disabled_channels',
    sa.Column('vk_group_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('vk_group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disabled_channels')
    # ### end Alembic commands ###
